// Generated by gencpp from file crospy/pub.msg
// DO NOT EDIT!


#ifndef CROSPY_MESSAGE_PUB_H
#define CROSPY_MESSAGE_PUB_H

#include <ros/service_traits.h>


#include <crospy/pubRequest.h>
#include <crospy/pubResponse.h>


namespace crospy
{

struct pub
{

typedef pubRequest Request;
typedef pubResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pub
} // namespace crospy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crospy::pub > {
  static const char* value()
  {
    return "f9f9aa5fef081d148fcc68ac90f825a1";
  }

  static const char* value(const ::crospy::pub&) { return value(); }
};

template<>
struct DataType< ::crospy::pub > {
  static const char* value()
  {
    return "crospy/pub";
  }

  static const char* value(const ::crospy::pub&) { return value(); }
};


// service_traits::MD5Sum< ::crospy::pubRequest> should match 
// service_traits::MD5Sum< ::crospy::pub > 
template<>
struct MD5Sum< ::crospy::pubRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crospy::pub >::value();
  }
  static const char* value(const ::crospy::pubRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crospy::pubRequest> should match 
// service_traits::DataType< ::crospy::pub > 
template<>
struct DataType< ::crospy::pubRequest>
{
  static const char* value()
  {
    return DataType< ::crospy::pub >::value();
  }
  static const char* value(const ::crospy::pubRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crospy::pubResponse> should match 
// service_traits::MD5Sum< ::crospy::pub > 
template<>
struct MD5Sum< ::crospy::pubResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crospy::pub >::value();
  }
  static const char* value(const ::crospy::pubResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crospy::pubResponse> should match 
// service_traits::DataType< ::crospy::pub > 
template<>
struct DataType< ::crospy::pubResponse>
{
  static const char* value()
  {
    return DataType< ::crospy::pub >::value();
  }
  static const char* value(const ::crospy::pubResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSPY_MESSAGE_PUB_H
