// Generated by gencpp from file crospy/pubRequest.msg
// DO NOT EDIT!


#ifndef CROSPY_MESSAGE_PUBREQUEST_H
#define CROSPY_MESSAGE_PUBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crospy
{
template <class ContainerAllocator>
struct pubRequest_
{
  typedef pubRequest_<ContainerAllocator> Type;

  pubRequest_()
    : type()
    , layer()  {
    }
  pubRequest_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , layer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _layer_type;
  _layer_type layer;





  typedef boost::shared_ptr< ::crospy::pubRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crospy::pubRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pubRequest_

typedef ::crospy::pubRequest_<std::allocator<void> > pubRequest;

typedef boost::shared_ptr< ::crospy::pubRequest > pubRequestPtr;
typedef boost::shared_ptr< ::crospy::pubRequest const> pubRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crospy::pubRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crospy::pubRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crospy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crospy::pubRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crospy::pubRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crospy::pubRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crospy::pubRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crospy::pubRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crospy::pubRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crospy::pubRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3b94f6a3350dd883b7d7b8e1d639f430";
  }

  static const char* value(const ::crospy::pubRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3b94f6a3350dd883ULL;
  static const uint64_t static_value2 = 0xb7d7b8e1d639f430ULL;
};

template<class ContainerAllocator>
struct DataType< ::crospy::pubRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crospy/pubRequest";
  }

  static const char* value(const ::crospy::pubRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crospy::pubRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string type\n\
string layer\n\
";
  }

  static const char* value(const ::crospy::pubRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crospy::pubRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.layer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pubRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crospy::pubRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crospy::pubRequest_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "layer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.layer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSPY_MESSAGE_PUBREQUEST_H
