// Generated by gencpp from file crospy/sub.msg
// DO NOT EDIT!


#ifndef CROSPY_MESSAGE_SUB_H
#define CROSPY_MESSAGE_SUB_H

#include <ros/service_traits.h>


#include <crospy/subRequest.h>
#include <crospy/subResponse.h>


namespace crospy
{

struct sub
{

typedef subRequest Request;
typedef subResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct sub
} // namespace crospy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crospy::sub > {
  static const char* value()
  {
    return "4096e8e9f96b81072bcc1faf81a24d83";
  }

  static const char* value(const ::crospy::sub&) { return value(); }
};

template<>
struct DataType< ::crospy::sub > {
  static const char* value()
  {
    return "crospy/sub";
  }

  static const char* value(const ::crospy::sub&) { return value(); }
};


// service_traits::MD5Sum< ::crospy::subRequest> should match 
// service_traits::MD5Sum< ::crospy::sub > 
template<>
struct MD5Sum< ::crospy::subRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crospy::sub >::value();
  }
  static const char* value(const ::crospy::subRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crospy::subRequest> should match 
// service_traits::DataType< ::crospy::sub > 
template<>
struct DataType< ::crospy::subRequest>
{
  static const char* value()
  {
    return DataType< ::crospy::sub >::value();
  }
  static const char* value(const ::crospy::subRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crospy::subResponse> should match 
// service_traits::MD5Sum< ::crospy::sub > 
template<>
struct MD5Sum< ::crospy::subResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crospy::sub >::value();
  }
  static const char* value(const ::crospy::subResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crospy::subResponse> should match 
// service_traits::DataType< ::crospy::sub > 
template<>
struct DataType< ::crospy::subResponse>
{
  static const char* value()
  {
    return DataType< ::crospy::sub >::value();
  }
  static const char* value(const ::crospy::subResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSPY_MESSAGE_SUB_H
