// Generated by gencpp from file crospy/subRequest.msg
// DO NOT EDIT!


#ifndef CROSPY_MESSAGE_SUBREQUEST_H
#define CROSPY_MESSAGE_SUBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crospy
{
template <class ContainerAllocator>
struct subRequest_
{
  typedef subRequest_<ContainerAllocator> Type;

  subRequest_()
    : client()  {
    }
  subRequest_(const ContainerAllocator& _alloc)
    : client(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _client_type;
  _client_type client;





  typedef boost::shared_ptr< ::crospy::subRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crospy::subRequest_<ContainerAllocator> const> ConstPtr;

}; // struct subRequest_

typedef ::crospy::subRequest_<std::allocator<void> > subRequest;

typedef boost::shared_ptr< ::crospy::subRequest > subRequestPtr;
typedef boost::shared_ptr< ::crospy::subRequest const> subRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crospy::subRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crospy::subRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crospy

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crospy::subRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crospy::subRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crospy::subRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crospy::subRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crospy::subRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crospy::subRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crospy::subRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a3397efab4a31b69099037ec38e22ec9";
  }

  static const char* value(const ::crospy::subRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa3397efab4a31b69ULL;
  static const uint64_t static_value2 = 0x099037ec38e22ec9ULL;
};

template<class ContainerAllocator>
struct DataType< ::crospy::subRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crospy/subRequest";
  }

  static const char* value(const ::crospy::subRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crospy::subRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string client\n\
";
  }

  static const char* value(const ::crospy::subRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crospy::subRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.client);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct subRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crospy::subRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crospy::subRequest_<ContainerAllocator>& v)
  {
    s << indent << "client: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.client);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSPY_MESSAGE_SUBREQUEST_H
