// Generated by gencpp from file croscpp/layer_msgType.msg
// DO NOT EDIT!


#ifndef CROSCPP_MESSAGE_LAYER_MSGTYPE_H
#define CROSCPP_MESSAGE_LAYER_MSGTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace croscpp
{
template <class ContainerAllocator>
struct layer_msgType_
{
  typedef layer_msgType_<ContainerAllocator> Type;

  layer_msgType_()
    : name()  {
    }
  layer_msgType_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::croscpp::layer_msgType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::croscpp::layer_msgType_<ContainerAllocator> const> ConstPtr;

}; // struct layer_msgType_

typedef ::croscpp::layer_msgType_<std::allocator<void> > layer_msgType;

typedef boost::shared_ptr< ::croscpp::layer_msgType > layer_msgTypePtr;
typedef boost::shared_ptr< ::croscpp::layer_msgType const> layer_msgTypeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::croscpp::layer_msgType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::croscpp::layer_msgType_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace croscpp

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'croscpp': ['/media/sf_VirtualUbuntu1604/catkin_ws/src/croscpp/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::croscpp::layer_msgType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::croscpp::layer_msgType_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::croscpp::layer_msgType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::croscpp::layer_msgType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::croscpp::layer_msgType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::croscpp::layer_msgType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::croscpp::layer_msgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::croscpp::layer_msgType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::croscpp::layer_msgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "croscpp/layer_msgType";
  }

  static const char* value(const ::croscpp::layer_msgType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::croscpp::layer_msgType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name \n\
";
  }

  static const char* value(const ::croscpp::layer_msgType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::croscpp::layer_msgType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct layer_msgType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::croscpp::layer_msgType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::croscpp::layer_msgType_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSCPP_MESSAGE_LAYER_MSGTYPE_H
